'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Loader2, MailPlus, RefreshCw, ShieldCheck, UserRoundX } from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { supabase } from '@/lib/supabase';
import { createGuardianInvitation, manageGuardianInvitation } from '@/lib/guardian/onboarding';

type Connection = { record_type: 'relationship'|'invitation'; record_id: string; guardian_name: string; guardian_email: string|null; relationship_type: string; is_primary: boolean; status: string; invitation_type: string|null; expires_at: string|null; created_at: string; permissions: Array<{key:string;state:string;controlledBy:string}> };

export default function PlayerGuardiansPage() {
  const { user } = useAuth();
  const [connections,setConnections]=useState<Connection[]>([]); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [relationship,setRelationship]=useState<'parent'|'legal_guardian'|'authorised_guardian'>('parent');
  const [dob,setDob]=useState(''); const [reason,setReason]=useState('');
  const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.rpc('player_get_guardian_connections');setConnections((data??[]) as Connection[]);setMessage(error?.message??null);setLoading(false);},[]);
  useEffect(()=>{void load();},[load]);
  const invite=async(e:React.FormEvent)=>{e.preventDefault();if(!user)return;setWorking(true);setMessage(null);const result=await createGuardianInvitation({playerId:user.id,guardianEmail:email,guardianName:name,relationshipType:relationship,isPrimary:connections.every(item=>!item.is_primary)});setWorking(false);setMessage(result.error||'Secure invitation sent.');if(!result.error){setName('');setEmail('');void load();}};
  const manage=async(action:'resend'|'cancel',id:string)=>{setWorking(true);const result=await manageGuardianInvitation(action,id);setWorking(false);setMessage(result.error||`Invitation ${action==='resend'?'sent again':'cancelled'}.`);if(!result.error)void load();};
  const correction=async(e:React.FormEvent)=>{e.preventDefault();setWorking(true);const {error}=await supabase.rpc('player_request_dob_correction',{p_requested_date_of_birth:dob,p_reason:reason});setWorking(false);setMessage(error?.message||'Date-of-birth correction submitted for review.');if(!error){setDob('');setReason('');}};
  const adultDecision=async(id:string,decision:string)=>{setWorking(true);const {error}=await supabase.rpc('player_decide_adult_guardian_access',{p_relationship_id:id,p_decision:decision});setWorking(false);setMessage(error?.message||'Guardian access decision saved.');if(!error)void load();};
  const revoke=async(id:string)=>{if(!window.confirm('End this Guardian relationship and remove its access?'))return;setWorking(true);const {error}=await supabase.rpc('revoke_guardian_relationship',{p_relationship_id:id,p_reason:'Revoked by Player'});setWorking(false);setMessage(error?.message||'Guardian relationship revoked.');if(!error)void load();};
  return <div className="min-h-screen px-4 py-7 text-white"><div className="mx-auto max-w-md space-y-5"><header><Link href="/profile" className="inline-flex items-center gap-2 text-sm text-gray-400"><ArrowLeft size={17}/>Profile</Link><h1 className="mt-3 text-3xl font-bold">Guardians & privacy</h1><p className="mt-2 text-sm text-gray-400">See exactly who is connected, their status, and the limited permissions applied.</p></header>
    {message?<p className="rounded-xl border border-white/10 bg-white/[0.04] p-3 text-sm">{message}</p>:null}
    <section className="glass-card p-5"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck className="text-[var(--accent-primary)]" size={19}/>Connections</h2>{loading?<Loader2 className="mx-auto my-7 animate-spin"/>:<div className="mt-4 space-y-3">{connections.length===0?<p className="text-sm text-gray-500">No Guardian connection yet.</p>:connections.map(item=><article key={item.record_id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.guardian_name}</p><p className="text-xs text-gray-500">{item.guardian_email} · {item.relationship_type.replaceAll('_',' ')}</p></div><span className="h-fit rounded-full bg-white/[0.06] px-2 py-1 text-[10px] uppercase">{item.status.replaceAll('_',' ')}</span></div>{item.permissions.length?<details className="mt-3 text-xs"><summary className="cursor-pointer text-[var(--accent-primary)]">View permissions</summary><ul className="mt-2 space-y-1 text-gray-400">{item.permissions.map(p=><li key={p.key}>{p.key.replaceAll('_',' ')}: {p.state.replaceAll('_',' ')}</li>)}</ul></details>:null}{item.record_type==='invitation'&&['sent','delivered','opened','expired','pending'].includes(item.status)?<div className="mt-3 flex gap-2"><button disabled={working} onClick={()=>manage('resend',item.record_id)} className="flex min-h-10 flex-1 items-center justify-center gap-1 rounded-lg border border-white/15 text-xs"><RefreshCw size={14}/>Resend</button><button disabled={working} onClick={()=>manage('cancel',item.record_id)} className="min-h-10 flex-1 rounded-lg border border-red-300/20 text-xs text-red-200">Cancel</button></div>:null}{item.record_type==='relationship'&&item.status==='suspended'?<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>adultDecision(item.record_id,'limited_calendar')} className="rounded-lg border border-white/15 p-2 text-xs">Allow calendar only</button><button onClick={()=>adultDecision(item.record_id,'limited_safety')} className="rounded-lg border border-white/15 p-2 text-xs">Allow safety only</button><button onClick={()=>adultDecision(item.record_id,'limited_standard')} className="rounded-lg border border-white/15 p-2 text-xs">Allow limited overview</button><button onClick={()=>adultDecision(item.record_id,'remove')} className="rounded-lg border border-red-300/20 p-2 text-xs text-red-200">Remove access</button></div>:null}{item.record_type==='relationship'&&['active','adult_authorised','pending'].includes(item.status)?<button disabled={working} onClick={()=>revoke(item.record_id)} className="mt-3 min-h-10 w-full rounded-lg border border-red-300/20 text-xs text-red-200">End relationship</button>:null}</article>)}</div>}</section>
    <form onSubmit={invite} className="glass-card space-y-3 p-5"><h2 className="flex items-center gap-2 font-bold"><MailPlus size={19}/>Invite another Guardian</h2><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Guardian name" className="w-full rounded-xl border border-white/10 bg-black/30 p-3"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Guardian email" className="w-full rounded-xl border border-white/10 bg-black/30 p-3"/><select value={relationship} onChange={e=>setRelationship(e.target.value as typeof relationship)} className="w-full rounded-xl border border-white/10 bg-[#171817] p-3"><option value="parent">Parent</option><option value="legal_guardian">Legal Guardian</option><option value="authorised_guardian">Authorised Guardian</option></select><button disabled={working} className="min-h-11 w-full rounded-xl bg-[var(--accent-primary)] font-bold text-black">Send invitation</button></form>
    <form onSubmit={correction} className="glass-card space-y-3 p-5"><h2 className="flex items-center gap-2 font-bold"><UserRoundX size={19}/>Correct date of birth</h2><p className="text-xs text-gray-500">DOB is not displayed here. Corrections are reviewed because they can change Guardian requirements.</p><input required type="date" max={new Date().toISOString().slice(0,10)} value={dob} onChange={e=>setDob(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/30 p-3"/><textarea required minLength={10} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what needs correcting" className="min-h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3"/><button disabled={working} className="min-h-11 w-full rounded-xl border border-white/15 font-semibold">Submit correction request</button></form>
  </div></div>;
}
