'use client';

import { useEffect, useState } from 'react';
import { Bell, Eye, LockKeyhole, Mail, Smartphone } from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { supabase } from '@/lib/supabase';
import { loadNotificationPreferences, saveNotificationPreferences } from '@/lib/guardian/api';
import type { GuardianNotificationPreferences } from '@/lib/guardian/types';
import { GuardianError, GuardianLoading, GuardianPageHeader } from '../GuardianUi';

const options = [
  ['schedule_changes','Schedule changes'],['event_cancellations','Event cancellations'],['attendance_updates','Attendance updates'],
  ['rsvp_reminders','RSVP reminders'],['coach_announcements','Coach announcements'],['injury_alerts','Injury alerts'],
  ['high_pain_alerts','High-pain alerts'],['readiness_safety_alerts','Readiness safety alerts'],['permission_changes','Permission changes'],
  ['relationship_changes','Relationship changes'],['product_updates','Product updates'],
] as const;
const defaults = Object.fromEntries(options.map(([key])=>[key,true])) as Record<string,boolean>;

export function GuardianSettingsPage() {
  const { user, availableRoles, switchRole } = useAuth();
  const [preferences,setPreferences]=useState<GuardianNotificationPreferences|null>(null);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
  const [requestType,setRequestType]=useState('data_export'); const [requestDetails,setRequestDetails]=useState(''); const [requesting,setRequesting]=useState(false);
  useEffect(()=>{if(!user)return;void loadNotificationPreferences(user.id).then(result=>{setPreferences(result.data??{guardian_user_id:user.id,in_app:defaults,email:{},push:{}});setError(result.error);setLoading(false);});},[user]);
  const toggle=(key:string)=>setPreferences(current=>current?({...current,in_app:{...current.in_app,[key]:!(current.in_app[key]??true)}}):current);
  const save=async()=>{if(!preferences)return;setSaving(true);setError(null);const nextError=await saveNotificationPreferences(preferences);setError(nextError);setSuccess(nextError?null:'Notification preferences saved.');setSaving(false);};
  const submit=async()=>{setRequesting(true);setError(null);const {error:nextError}=await supabase.rpc('create_guardian_privacy_request',{p_request_type:requestType,p_related_player_id:null,p_related_relationship_id:null,p_details:requestDetails||null});setRequesting(false);setError(nextError?.message??null);setSuccess(nextError?null:'Privacy request submitted.');if(!nextError)setRequestDetails('');};
  const changeWorkspace=async(role:'player'|'coach')=>{const result=await switchRole(role);if(result.error){setError(result.error);return;}window.location.assign(role==='coach'?'/coach':'/');};
  if(loading||!preferences)return <GuardianLoading label="Loading Guardian settings…"/>;
  return <div className="mx-auto max-w-6xl space-y-6"><GuardianPageHeader title="Settings" description="Guardian-specific notifications, privacy requests, and accessibility information."/>{error?<GuardianError message={error}/>:null}<div className="grid gap-4 lg:grid-cols-2">
    <section className="glass-card p-5"><div className="flex items-center gap-2"><Bell size={17} className="text-[var(--accent-primary)]"/><h2 className="text-sm font-semibold">In-app notifications</h2></div><div className="mt-4 space-y-2">{options.map(([key,label])=><label key={key} className="flex min-h-12 cursor-pointer items-center justify-between gap-3 rounded-xl border border-white/10 px-3"><span className="text-sm text-gray-300">{label}</span><input type="checkbox" checked={preferences.in_app[key]??true} onChange={()=>toggle(key)} className="h-5 w-5 accent-[var(--accent-primary)]"/></label>)}</div><button onClick={()=>void save()} disabled={saving} className="mt-4 min-h-11 rounded-xl bg-[var(--accent-primary)] px-4 text-sm font-bold text-black disabled:opacity-60">{saving?'Saving…':'Save preferences'}</button>{success?<p className="mt-3 text-xs text-[var(--status-green)]">{success}</p>:null}</section>
    <div className="space-y-4"><section className="glass-card p-5"><h2 className="text-sm font-semibold">Delivery and workspaces</h2><div className="mt-4 space-y-3"><div className="flex items-start gap-3 rounded-xl border border-white/10 p-4"><Mail className="shrink-0 text-gray-500" size={18}/><div><p className="text-sm font-medium">Security email</p><p className="mt-1 text-xs text-gray-500">Guardian invitations and reminders use verified Gmail SMTP delivery when configured.</p></div></div><div className="flex items-start gap-3 rounded-xl border border-white/10 p-4"><Smartphone className="shrink-0 text-gray-500" size={18}/><div><p className="text-sm font-medium">Push notifications</p><p className="mt-1 text-xs text-gray-500">Push is reserved for a future provider. Important notices remain available in-app.</p></div></div></div>{availableRoles.includes('player')?<button onClick={()=>void changeWorkspace('player')} className="mt-4 min-h-11 w-full rounded-xl border border-white/15 text-sm font-semibold">Switch to Player workspace</button>:null}{availableRoles.includes('coach')?<button onClick={()=>void changeWorkspace('coach')} className="mt-2 min-h-11 w-full rounded-xl border border-white/15 text-sm font-semibold">Switch to Coach workspace</button>:null}</section>
      <section id="privacy" className="glass-card p-5"><div className="flex items-center gap-2"><LockKeyhole size={17} className="text-[var(--accent-primary)]"/><h2 className="text-sm font-semibold">Privacy request</h2></div><p className="mt-2 text-xs text-gray-500">Destructive requests require identity confirmation and human review before fulfilment.</p><div className="mt-4 space-y-3"><select value={requestType} onChange={event=>setRequestType(event.target.value)} className="w-full rounded-xl border border-white/10 bg-[#171817] p-3 text-sm"><option value="data_export">Data export</option><option value="correction">Correction</option><option value="account_deletion">Account deletion</option><option value="relationship_removal">Relationship removal</option><option value="withdraw_optional_consent">Withdraw optional consent</option><option value="report_unauthorised_access">Report unauthorised access</option><option value="report_incorrect_relationship">Report incorrect relationship</option></select><textarea value={requestDetails} onChange={event=>setRequestDetails(event.target.value)} maxLength={4000} placeholder="Details (optional)" className="min-h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-sm"/><button onClick={()=>void submit()} disabled={requesting} className="min-h-11 w-full rounded-xl bg-[var(--accent-primary)] text-sm font-bold text-black disabled:opacity-60">{requesting?'Submitting…':'Submit privacy request'}</button></div><div className="mt-4 grid grid-cols-2 gap-2"><a href="/guardian/children" className="flex min-h-11 items-center justify-center rounded-xl border border-white/15 text-sm font-semibold">Relationships</a><a href="/guardian/permissions" className="flex min-h-11 items-center justify-center rounded-xl border border-white/15 text-sm font-semibold">Permissions</a></div></section>
      <section className="glass-card p-5"><div className="flex items-center gap-2"><Eye size={17} className="text-[var(--accent-primary)]"/><h2 className="text-sm font-semibold">Appearance and accessibility</h2></div><p className="mt-3 text-sm leading-relaxed text-gray-400">Guardian pages use Lodario&apos;s keyboard focus styles, reduced-motion preferences, responsive cards, and large touch targets.</p></section>
    </div></div></div>;
}
