'use client';

import { useCallback, useEffect, useState } from 'react';
import { Loader2, MailPlus, ShieldCheck } from 'lucide-react';
import { useCoachTeam } from '@/lib/coach/selectedTeam';
import { supabase } from '@/lib/supabase';
import { createGuardianInvitation } from '@/lib/guardian/onboarding';

type Status = { player_id:string; player_name:string; age_policy_category:string; account_state:string; guardian_status:string; guardian_count:number; pending_invitation_count:number };

export default function CoachGuardiansPage(){
  const {selectedTeam}=useCoachTeam(); const [rows,setRows]=useState<Status[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [selected,setSelected]=useState(''); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [sending,setSending]=useState(false);
  const load=useCallback(async()=>{if(!selectedTeam){setRows([]);return;}setLoading(true);const {data,error:nextError}=await supabase.rpc('coach_get_guardian_status',{p_team_id:selectedTeam.id});setRows((data??[]) as Status[]);setError(nextError?.message??null);setLoading(false);},[selectedTeam]);
  useEffect(()=>{void load();},[load]);
  const invite=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedTeam||!selected)return;setSending(true);setError(null);const result=await createGuardianInvitation({playerId:selected,guardianEmail:email,guardianName:name,relationshipType:'parent',isPrimary:false,invitationType:'coach_initiated',relatedTeamId:selectedTeam.id});setSending(false);setError(result.error||'Secure Guardian invitation sent.');if(!result.error){setName('');setEmail('');void load();}};
  return <div className="mx-auto max-w-6xl space-y-5"><header><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--accent-primary)]">Team operations</p><h1 className="mt-2 text-3xl font-bold text-white">Guardian status</h1><p className="mt-2 text-sm text-gray-400">Operational linking status only. Player dates of birth and private Guardian verification data are never shown.</p></header>{!selectedTeam?<div className="glass-card p-6 text-sm text-gray-400">Choose a team to view Guardian linking status.</div>:<><section className="glass-card overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck className="text-[var(--accent-primary)]"/>Players</h2></div>{loading?<Loader2 className="mx-auto my-10 animate-spin text-[var(--accent-primary)]"/>:<div className="divide-y divide-white/10">{rows.map(row=><div key={row.player_id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-semibold text-white">{row.player_name}</p><p className="text-xs text-gray-500">{row.age_policy_category.replaceAll('_',' ')} · account {row.account_state.replaceAll('_',' ')}</p></div><span className="rounded-full bg-white/[0.05] px-3 py-1 text-xs text-gray-300">{row.guardian_status.replaceAll('_',' ')}</span><button onClick={()=>setSelected(row.player_id)} className="min-h-10 rounded-lg border border-white/15 px-3 text-xs font-semibold">Invite</button></div>)}{rows.length===0?<p className="p-6 text-sm text-gray-500">No active Players in this team.</p>:null}</div>}</section><form onSubmit={invite} className="glass-card grid gap-3 p-5 sm:grid-cols-2"><h2 className="flex items-center gap-2 font-bold sm:col-span-2"><MailPlus size={19}/>Coach-initiated invitation</h2><select required value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-xl border border-white/10 bg-[#171817] p-3 text-white"><option value="">Select Player</option>{rows.map(row=><option key={row.player_id} value={row.player_id}>{row.player_name}</option>)}</select><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Guardian name" className="rounded-xl border border-white/10 bg-black/30 p-3 text-white"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Guardian email" className="rounded-xl border border-white/10 bg-black/30 p-3 text-white sm:col-span-2"/><p className="text-xs text-gray-500 sm:col-span-2">The Coach can initiate an operational, limited invitation but cannot approve the Player account or see consent answers.</p><button disabled={sending} className="min-h-11 rounded-xl bg-[var(--accent-primary)] font-bold text-black sm:col-span-2">{sending?'Sending…':'Send secure invitation'}</button></form></>}{error?<p className="rounded-xl border border-red-300/20 bg-red-300/10 p-3 text-sm text-red-200">{error}</p>:null}</div>;
}
